select * from customer limit 5
--Q1. what is the total revenue generated by male vs female customers?
select gender,SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. which customer used a discount but spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount) from customer)

--Q3. which are the top 5 products with the highest average review rating?
select item_purchased,ROUND(AVG (review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. compare the average purchase amounts between standard and express shipping?
select shipping_type,ROUND(AVG(purchase_amount::numeric),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. do subscribed customers spend more? compare avarage spend and total revenue between subscribers and non subscribers.
select subscription_status,
SUM(purchase_amount) as total_revenue,
ROUND(AVG(purchase_amount::numeric),2) as average_spend,
COUNT(customer_id) as "total customers"
from customer
group by subscription_status
order by total_revenue,average_spend desc;

--Q6. which 5 products have the highest persentage of purchases with discounts applied?
select item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied='Yes' then 1 else 0 end)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. segment customers into new,returning,loyal based on their total number of previous purchases,and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
CASE 
  when previous_purchases = 1 then 'New'
  when previous_purchases between 2 and 10 then 'Retuning'
  else 'loyal'
  end as customer_segment
from customer
)
select customer_segment,count(*) as number_of_customers
from customer_type
group by customer_segment

--Q8. what are the top 3 most purchased products with in each catagory?
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Q9. Are customers who are repeate buyers(more than 5 previos purchases)also likely to subscribe?

select subscription_status,count(customer_id) as repeate_buyers
from customer
where previous_purchases > 5
group by subscription_status

--10. what is the revenue contribution of each age gap
select age_group,sum(purchase_amount) as revenue 
from customer
group by age_group
order by revenue desc